### ISSUE TITLE
你好，我在项目文件里并没有找到requirements.txt，能问一下是什么情况吗

### ISSUE THREAD

**Issue by SINGER826** [Faker-lz/Topic_and_user_profile_analysis_system#1]
![image](https://user-images.githubusercontent.com/59014447/166489702-c20bc737-ada2-4a38-9023-8251d479e92e.png)

**Comment by SINGER826** [comment]
求一个联系方式

**Comment by chungmuroad** [comment]
> 求一个联系方式

你解决了吗？

**Comment by HE-SIQUN** [comment]
> 

现在又requirement了嘛

**Comment by HE-SIQUN** [comment]
现在有requirement了嘛

**Comment by Faker-lz** [comment]
您好，是我在开发的时候把requitement.txt文件忽略了，一直忘记上传，我会在近期处理，感谢提问
