### ISSUE TITLE
psyco无法安装

### ISSUE THREAD

**Issue by liuyizhuo11235** [Faker-lz/Topic_and_user_profile_analysis_system#10]
大佬，安装不了psyco呀，pip提示psyco已经不存在了，到psyco官网下载后又不支持win64位系统，请问你是怎么安装的啊？

**Comment by Respectzz** [comment]
我也在好奇这个情况

**Comment by Faker-lz** [comment]
你好，我刚刚尝试在我的环境里使用psyco，发现现在也无法找到，但是并不影响后端的运行，感谢提问，已修正requestment.txt文件。
