### ISSUE TITLE
weibo_crawler项目selector_parser中的search_weibo_parser.py的_parse_weibo函数无法获取content

### ISSUE THREAD

**Issue by huhusmang** [Faker-lz/Topic_and_user_profile_analysis_system#3]
说明：

1. 项目环境部署完成，能够运行
2. cookie正确，能够解析到正确的html内容

看了一下目前的微博前端，相关的xpath路径好像做了改变，根据项目的xpath路径无法获得content。

**Comment by Faker-lz** [comment]
那对应xpath路径部分需要做一些修改，稍等我几天哈

**Comment by huhusmang** [comment]
可以讨论一下嘛🤔

**Comment by Faker-lz** [comment]
您好，我这几天比较忙，就没来得及修复，我私信你我们先讨论一下吧。

**Comment by Faker-lz** [comment]
有什么问题欢迎在这里讨论，我看到了会及时解决

**Comment by tay10rb** [comment]
有同样的问题，尝试修改但没成功

**Comment by guanxijing** [comment]
确实有问题，我搞不定，作者能搞定吗

**Comment by Faker-lz** [comment]
我突然想到可能是你们没有配置自己的微博爬虫cookie，所以按照[weibo_crawler](https://github.com/Faker-lz/Topic_and_user_profile_analysis_system/tree/master/code/weibo_crawler)下的readme配置以下应该可以解决问题

**Comment by tay10rb** [comment]
配置了的，有些接口可以parese，有些不行了。作者都可以爬取成功吗

**Comment by Faker-lz** [comment]
我看了一下，是微博服务器的“粉丝数量”这个词条数据变了，比如原来是“10000”，现在变成了“粉丝数是1万”，同样好友数也编程文字描述的了

**Comment by Faker-lz** [comment]
我看了一下，微博服务器上关于用户粉丝数和好友数词条数据发生了变化，比如原来粉丝数据为“10000”，现在变成了“粉丝数是1万”，我会将相关字段从整数类型变为字符串类型，来保证爬虫的稳定性，但是分析系统需要加入对应的解析。更新的爬虫服务我会很快传上来，分析系统则需要一段时间。

**Comment by Faker-lz** [comment]
> 我看了一下，微博服务器上关于用户粉丝数和好友数词条数据发生了变化，比如原来粉丝数据为“10000”，现在变成了“粉丝数是1万”，我会将相关字段从整数类型变为字符串类型，来保证爬虫的稳定性，但是分析系统需要加入对应的解析。更新的爬虫服务我会很快传上来，分析系统则需要一段时间。

现在我已经修复好了爬虫，用正则表达式进行了相关数据的处理，`好友数`和`粉丝数`字段仍然是整数类型，也就是说不用再修改分析系统后端，相关代码已经发布。如有问题，欢迎继续讨论。

**Comment by huhusmang** [comment]
`created_at = sel.xpath(
                    '(.//p[@class="from"])[last()]/a[1]/text()')[0].replace(' ', '').replace('\n', '').split('前')[0],
weibo['weibo_id'] = sel.xpath('(.//div[@class="from"])[last()]/a[1]/@href')[0].split('/')[-1].split('?')[0]
`
search_weibo_parser.py _parse_weibo()函数的这两个xpath不正确，p标签应该改为div

**Comment by guanxijing** [comment]
感谢大佬，厉害了，更新完，你弄个打赏，我去打赏




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月28日(星期二) 下午5:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Faker-lz/Topic_and_user_profile_analysis_system] weibo_crawler项目selector_parser中的search_weibo_parser.py的_parse_weibo函数无法获取content (Issue #3)





  
我看了一下，微博服务器上关于用户粉丝数和好友数词条数据发生了变化，比如原来粉丝数据为“10000”，现在变成了“粉丝数是1万”，我会将相关字段从整数类型变为字符串类型，来保证爬虫的稳定性，但是分析系统需要加入对应的解析。更新的爬虫服务我会很快传上来，分析系统则需要一段时间。
  
现在我已经修复好了爬虫，用正则表达式进行了相关数据的处理，好友数和粉丝数字段仍然是整数类型，也就是说不用再修改分析系统后端，相关代码已经发布。如有问题，欢迎继续讨论。

**Comment by Faker-lz** [comment]
![image](https://user-images.githubusercontent.com/61659265/222120075-e1510f37-2642-4ea2-9c65-3677bd941f34.png)如图，按照你指出的错误进行修改后出现报错，能否提供你的运行截图。


> `created_at = sel.xpath( '(.//p[@class="from"])[last()]/a[1]/text()')[0].replace(' ', '').replace('\n', '').split('前')[0], weibo['weibo_id'] = sel.xpath('(.//div[@class="from"])[last()]/a[1]/@href')[0].split('/')[-1].split('?')[0] ` search_weibo_parser.py _parse_weibo()函数的这两个xpath不正确，p标签应该改为div

**Comment by Faker-lz** [comment]
> 感谢大佬，厉害了，更新完，你弄个打赏，我去打赏
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年2月28日(星期二) 下午5:27 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Faker-lz/Topic_and_user_profile_analysis_system] weibo_crawler项目selector_parser中的search_weibo_parser.py的_parse_weibo函数无法获取content (Issue #3) 我看了一下，微博服务器上关于用户粉丝数和好友数词条数据发生了变化，比如原来粉丝数据为“10000”，现在变成了“粉丝数是1万”，我会将相关字段从整数类型变为字符串类型，来保证爬虫的稳定性，但是分析系统需要加入对应的解析。更新的爬虫服务我会很快传上来，分析系统则需要一段时间。 现在我已经修复好了爬虫，用正则表达式进行了相关数据的处理，好友数和粉丝数字段仍然是整数类型，也就是说不用再修改分析系统后端，相关代码已经发布。如有问题，欢迎继续讨论。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

哈哈哈，感谢兄弟支持，目前项目存在很多缺陷，暂时不打算开放打赏功能，希望大家能够多提意见，有bug及时反馈，你们的交流就是对我最大的支持。另外由于我最近在忙考研复试和毕业设计，有些问题不能及时解决，还请见谅。
